### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by sharkweek** [dmarc3/vscode-nastran#16]
Can you post information about contribution to the repo? I love what you're doing and would like to see if I can use your work as a baseline for similar support for NX Nastran.

**Comment by dmarc3** [comment]
hey @sharkweek , thanks for the interest in contributing! I'll pull together a `CONTRIBUTING..md` and a `CODE_OF_CONDUCT.md` in the next day or so. If you're eager to get started, go ahead and fork the project and get started.

**Comment by sharkweek** [comment]
Not to add to your workoad, but any chance a Discord channel could be part of it? =)

**Comment by dmarc3** [comment]
Give [this](https://discord.gg/vVwDVUF3w5) a try. It's pretty empty for now.

**Comment by dmarc3** [comment]
Closed with #20
