### ISSUE TITLE
F6 doesnt work

### ISSUE THREAD

**Issue by zineddine999** [dmarc3/vscode-nastran#67]
Hello i want to change the command excute i have this issue : 

  + CategoryInfo          : ObjectNotFound: (nastran:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException"

How can i change the code of this command ? thanks

**Comment by dmarc3** [comment]
Hi @zineddine999 , the `F6` keybind that comes packaged with this extension assumes you have the `nastran` executable on your system path variable. I will update the `README.md` to state this explicitly. i.e. you need to be able to open any command window and execute `nastran -v` successfully. If you update your system path to include the path to your `nastran` executable, it should work. For reference, the path to my 2021.4 nastran executable looks like this:

```
C:\appl\MSC\Nastran\20214\bin
```

For what it's worth, you can also overwrite the `F6` keybind by editing your `keybindings.json` file to do whatever you want. See [here](https://code.visualstudio.com/docs/getstarted/keybindings) for vscode documentation on custom keybinds. See [here](https://code.visualstudio.com/docs/editor/variables-reference) for a helpful reference on vscode variables. Using [this](https://stackoverflow.com/a/52786528/21800534) as a guide, adding something like this could do something similar and would overwrite the `F6` keybind:

```
{
        "key": "F6",
        "command": "workbench.action.terminal.sendSequence",
        "args": {
          "text": "C:/PATH/TO/NASTRAN/nastran ${file}\u000D"
        }
}
```

**Comment by dmarc3** [comment]
@zineddine999 Can you confirm this solution works for you? If not, can you provide more information on your issue?

**Comment by zineddine999** [comment]
Oh sorry, it works. Thank you
